FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

# Устанавливаем рабочую директорию
WORKDIR /grpc

# Копируем файл зависимостей
COPY requirements.txt .


# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
ADD ./client /grpc/

# Устанавливаем PYTHONPATH
ENV PYTHONPATH="/grpc_python_server"

# Запускаем клиента
CMD ["python", "client/grpc_client.py"]
