version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - POSTGRES_USER=constantine
      - POSTGRES_PASSWORD=dox123456
      - POSTGRES_DB=grpc_db  # Исправлено имя переменной
      - DB_HOST=postgres_db
      - DB_PORT=5432
    ports:
      - "50051:50051"
    depends_on:
      - postgres_db
    volumes:
      - .:/app  # Лучше уточнить путь
    networks:
      - grpc_network

  grpc_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - grpc_server
    networks:
      - grpc_network
    entrypoint: >  # Добавляем ожидание сервера
      sh -c 'while ! nc -z grpc_server 50051; do sleep 1; done; python client/client.py'

  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=constantine
      - POSTGRES_PASSWORD=dox123456
      - POSTGRES_DB=grpc_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - grpc_network

networks:
  grpc_network:
    driver: bridge

volumes:
  pgdata:
