FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

# Устанавливаем рабочую директорию
WORKDIR /grpc

# Копируем файл зависимостей
COPY requirements.txt .

#установка netcat
RUN apt-get update && apt-get install -y netcat-openbsd

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
ADD . .

# Устанавливаем PYTHONPATH
ENV PYTHONPATH="/grpc"

# Запускаем клиента
CMD ["python", "client/client.py"]
