version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - POSTGRES_USER=constantine
      - POSTGRES_PASSWORD=dox123456
      - POSTGRES_DB=grpc_db
      - DB_HOST=postgres_db
      - DB_PORT=5432  # Оставляем стандартный порт
    ports:
      - "50051:50051"
    depends_on:
      - postgres_db
    volumes:
      - .:/app
    networks:
      - grpc_network
    entrypoint: >
      sh -c 'until pg_isready -h $DB_HOST -p $DB_PORT -U $POSTGRES_USER; do
               echo "Waiting for Postgres to be ready...";
               sleep 2;
             done;
             echo "Postgres is ready! Starting gRPC server...";
             python server/grpc_server.py'

  grpc_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - grpc_server
    networks:
      - grpc_network
    entrypoint: >
      sh -c 'while ! nc -z grpc_server 50051; do sleep 1; done; python client/client.py'

  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=constantine
      - POSTGRES_PASSWORD=dox123456
      - POSTGRES_DB=grpc_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Внешний и внутренний порты совпадают
    networks:
      - grpc_network

networks:
  grpc_network:
    driver: bridge

volumes:
  pgdata:
